### ISSUE TITLE
Add property doCopyResourceToRelativePath(relativePath, newName)

### ISSUE THREAD

**Issue by seanpoder** [valtech/aem-easy-content-upgrade#104]
Currently it is not possible to copy a node to the same parent node without getting a javax.jcr.ItemExistsException (same node name) for this I suggest either of the following:

1. Create a new method "doCopyResourceToRelativePath(relativePath, newName)"
2. Use the current method "doCopyResourceToRelativePath(relativePath)" but add the functionality as the PageManager and change the node name to "Copy of nodeName".

Example to replicate the issue:
println aecu.contentUpgradeBuilder()
           .forResources((String[])["/content/mySite/myPage"])
           .doCopyResourceToRelativePath("/content/mySite")
	   .run()

**Comment by gruberrolandvaltech** [comment]
I think the error message is fine if the page is copied to its parent location. We should rather go for adding "doCopyResourceToRelativePath(relativePath, newName)" to support a new node name.

**Comment by roxana-muresan** [comment]
I opened a PR for this enhancement, but without covering point 2. because naming the copy as "Copy of ..." some node that is already present under the destination path might be misleading.
Not covered in this enhancement but it might make sense to do the same for moveResourceToRelativePath as a next ticket.
